name: PrisonPit
main: fun.oneline.prisonpit.Main
version: 0.1.1
author: oneka
softdepend:
  - OneLineAPI
  - PacketListenerAPI
  - PlaceHolderAPI
  - DreamNetworkCoreServer
  - ProtocolLib
description: PrisonPit plugin
commands:
  pay:
    usage: no
